[versions]
jimmer = "0.9.119"
loom = "1.14-SNAPSHOT"
minecraft = "1.21.11"
yarn = "1.21.11+build.3"
loader = "0.18.4"
publish = "0.8.4"
maven = "0.34.0"

[libraries]
jimmer = { module = "org.babyfish.jimmer:jimmer-sql-kotlin", version.ref = "jimmer" }
minecraft = { module = "com.mojang:minecraft", version.ref = "minecraft" }
fabric-yarn = { module = "net.fabricmc:yarn", version.ref = "yarn" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "loader" }

[plugins]
loom = { id = "fabric-loom", version.ref = "loom" }
publish = { id = "me.modmuss50.mod-publish-plugin", version.ref = "publish" }
maven = { id = "com.vanniktech.maven.publish", version.ref = "maven" }
